I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 203, in script
    python:
  File "game/script.rpy", line 205, in <module>
    if not file_exists():
TypeError: 'bool' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 203, in script
    python:
  File "C:\Users\EternalShrine Maiden\OneDrive\renpy-8.3.7-sdk\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\EternalShrine Maiden\OneDrive\renpy-8.3.7-sdk\renpy\python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 205, in <module>
    if not file_exists():
TypeError: 'bool' object is not callable

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
VEIL: Beneath The Surface 1.0
Sun Jun 15 22:01:04 2025
