I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 628, in script
    k "(The peculiar girl reaches out her hand.)"
Exception: Sayer 'k' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 628, in script
    k "(The peculiar girl reaches out her hand.)"
  File "C:\Users\heave\OneDrive\renpy-8.3.7-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "C:\Users\heave\OneDrive\renpy-8.3.7-sdk\renpy\ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\heave\OneDrive\renpy-8.3.7-sdk\renpy\ast.py", line 472, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'k' is not defined.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
VEIL: Beneath The Surface 1.0
Wed Jun 25 15:08:00 2025
